### ISSUE TITLE
Error reading unsupported column name

### ISSUE THREAD

**Issue by alex88** [livehelpnow/tds_ecto#68] opened 2018-12-01 06:36 UTC
Hi there, trying to integrate with an external database I get:
```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Tds.Tokens.decode_column_name/1
        (tds) lib/tds/tokens.ex:553: Tds.Tokens.decode_column_name(<<191, 45, 11, 78, 231, 219, 120, 253, 197, 135, 155, 23, 124, 206, 209, 201, 66, 142, 81, 250, 163, 144, 126, 147, 26, 249,183, 247, 42, 22, 215, 14, 133, 232, 230, 154, 119, 150, 140, 184, 141, 88, 239, 200, 229, 97, 198, 220, 167, 137, ...>>)
        (tds) lib/tds/tokens.ex:544: Tds.Tokens.decode_column/1
        (tds) lib/tds/tokens.ex:538: Tds.Tokens.decode_columns/3
        (tds) lib/tds/tokens.ex:103: Tds.Tokens.decode_token/2
        (tds) lib/tds/tokens.ex:52: Tds.Tokens.decode_tokens/2
        (tds) lib/tds/messages.ex:100: Tds.Messages.parse/4
        (tds) lib/tds/protocol.ex:415: Tds.Protocol.new_data/2
        (tds) lib/tds/protocol.ex:493: Tds.Protocol.send_query/2
```

could it be because the column names contains any strange char?

**Comment by mjaric** [comment] 2018-12-01 09:48
could you please post issue in [https://github.com/livehelpnow/tds/issues](https://github.com/livehelpnow/tds/issues)

Thanks

**Comment by mjaric** [comment] 2018-12-01 10:45
I tried to reproduce this by using chars from arbitrary languages but without any luck.

Once you post the issue in TDS repo, please if it is not an issue, post example that can reproduce this issue. I will close this issue here since it is not related to tds_ecto library.

**Closed as completed by mjaric** 2018-12-01 10:45 UTC
